spring.messages.encoding=UTF-8
spring.application.name=pizzaria
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.web.resources.cache.cachecontrol.no-cache=true
spring.messages.basename=messages

